[package]
name = "coins"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "coins"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

coins_integrity = { workspace = true } 
